--SQL> @C:\Users\melvi\SQL_Projects\Company\Company_Database_Deletion.txt

--@ company-data.sql

--DROP TABLE C_EMPLOYEE;
DROP TABLE C_EMPLOYEE CASCADE CONSTRAINTS;

--DROP TABLE C_DEPARTMENT; 
DROP TABLE C_DEPARTMENT CASCADE CONSTRAINTS; 


DROP TABLE C_DEPT_LOCATION;
--DROP TABLE C_DEPT_LOCATION  CONSTRAINTS;

--DROP TABLE C_WORKS_ON;
DROP TABLE C_WORKS_ON CASCADE CONSTRAINTS;


--DROP TABLE C_PROJECTS;
DROP TABLE C_PROJECTS CASCADE CONSTRAINTS;

--DROP TABLE C_DEPENDENTS;
DROP TABLE C_DEPENDENTS CASCADE CONSTRAINTS;

