
--*******************************
--Loading Company Database Tables:
--	C_EMPLOYEES
--	C_DEPARTMENT
--	C_DEP_LOCATION
--	C_WORKS_ON
--	C_PROJECTS
--	C_DEPENDENT
--*******************************

--CREATING THE C_EMPLOYEE TABLE:
CREATE TABLE C_EMPLOYEE
(
FIRST_NAME		VARCHAR(25),
MIDDLE_INITITAL 	CHAR,
LAST_NAME 		VARCHAR(25),
SSN			NUMBER(9),
BDATE 			DATE,
ADDRESS 		VARCHAR(40),
SEX 			CHAR,
SALARY 			NUMBER(9),
SUPERSSN 		NUMBER(9),
DNUM 			NUMBER(1)
);

--Primary Key
ALTER TABLE C_EMPLOYEE
ADD CONSTRAINT PK_C_EMPLOYEE
PRIMARY KEY(SSN);
COMMIT;


--CREATING THE C_DEPARTMENT TABLES:
CREATE TABLE C_DEPARTMENT
(
DEPT_NAME		VARCHAR(25),
DEPT_NUM		NUMBER(10),
MGR_SSN			NUMBER(9),
MGR_START_DATE		VARCHAR(25)
);

--Primary Key
ALTER TABLE C_DEPARTMENT
ADD CONSTRAINT PK_C_DEPARTMENT
PRIMARY KEY(DEPT_NUM);
COMMIT;


--CREATING THE C_DEPT_LOCATION TABLES:
CREATE TABLE C_DEPT_LOCATION
(
DEPT_LOCATION_NUM		NUMBER(10),
DEPT_LOCATION			VARCHAR(40)
);

--Primary Key
ALTER TABLE C_DEPT_LOCATION
ADD CONSTRAINT PK_C_DEPT_LOCATION
PRIMARY KEY(DEPT_LOCATION_NUM, DEPT_LOCATION);
COMMIT;


--CREATING THE C_WORKS_ON TABLES:
CREATE TABLE C_WORKS_ON
(
ESSN			NUMBER(9),
P_NUM			NUMBER(30),
HOURS			NUMBER(38)
);

--Primary Key
ALTER TABLE C_WORKS_ON
ADD CONSTRAINT PK_C_WORKS_ON
PRIMARY KEY(ESSN,P_NUM);
COMMIT;


--CREATING THE C_PROJECTS TABLES:
CREATE TABLE C_PROJECTS
(
PROJ_NAME		VARCHAR(25),
PROJ_NUM		NUMBER(30),
PROJ_LOCATION		VARCHAR(40),
PROJ_DEPT_NUM		NUMBER(10)
);

--Primary Key
ALTER TABLE C_PROJECTS
ADD CONSTRAINT PK_C_PROJECTS
PRIMARY KEY(PROJ_NUM);
COMMIT;



--CREATING THE C_DEPENDENTS TABLES:
CREATE TABLE C_DEPENDENTS
(
ESSN			NUMBER(9),
DEPENDENTS_NAME	VARCHAR(25),
SEX			CHAR,
BDATE			DATE,
RELATIONSHIP		VARCHAR(25)
);

--Primary Key
ALTER TABLE C_DEPENDENTS
ADD CONSTRAINTS PK_C_DEPENDENTS
PRIMARY KEY(ESSN,DEPENDENTS_NAME);
COMMIT;






--CREATING fOREIGN KEYS CONSTRAINTS FOR THE COMPANY DATABASE

--C_EMPLOYEE
ALTER TABLE C_EMPLOYEE
ADD CONSTRAINT FK_C_EMPLOYEE_DEPT_CODE
FOREIGN KEY(DNUM)
	REFERENCES C_DEPARTMENT(DEPT_NUM);

ALTER TABLE C_EMPLOYEE
ADD CONSTRAINT FK_C_EMPLOYEE_SUPERSSN
FOREIGN KEY(SUPERSSN)
	REFERENCES C_EMPLOYEE(SSN);


-- C_DEPARTMENT
ALTER TABLE C_DEPARTMENT
ADD CONSTRAINT FK_C_DEPARTMENT_MGR_SSN
FOREIGN KEY(MGR_SSN)
	REFERENCES C_EMPLOYEE(SSN);


--C_DEPT_LOCATION
ALTER TABLE C_DEPT_LOCATION
ADD CONSTRAINT FK_C_DEPT_LOCATION_NUM
FOREIGN KEY(DEPT_LOCATION_NUM)
	REFERENCES C_DEPARTMENT(DEPT_NUM);


--C_PROJECTS
ALTER TABLE C_PROJECTS
ADD CONSTRAINT FK_C_PROJECTS_DEPT_NUM
FOREIGN KEY(PROJ_DEPT_NUM)
	REFERENCES C_DEPARTMENT(DEPT_NUM);


--C_WORKS_ON
ALTER TABLE C_WORKS_ON
ADD CONSTRAINT FK_C_WORKS_ON_ESSN
FOREIGN KEY(ESSN)
	REFERENCES C_EMPLOYEE(SSN);

ALTER TABLE C_WORKS_ON
ADD CONSTRAINT FK_C_WORKS_ON_PNO
FOREIGN KEY(P_NUM)
	REFERENCES C_PROJECTS(PROJ_NUM);



--C_DEPENDENTS
ALTER TABLE C_DEPENDENTS
ADD CONSTRAINT FK_C_DEPENDENTS
FOREIGN KEY(ESSN)
	REFERENCES C_EMPLOYEE(SSN);



--CREATE NOT NULL CONSTRAINTS
ALTER TABLE C_EMPLOYEE
ADD CONSTRAINT NN_C_EMPLOYEE_FIRST_NAME
	CHECK(FIRST_NAME IS NOT NULL);

ALTER TABLE C_EMPLOYEE
ADD CONSTRAINT NN_C_EMPLOYEE_LAST_NAME
	CHECK(LAST_NAME IS NOT NULL);

ALTER TABLE C_EMPLOYEE
ADD CONSTRAINT NN_C_EMPLOYEE_SSN
	CHECK(SSN IS NOT NULL);

ALTER TABLE C_EMPLOYEE
ADD CONSTRAINT NN_C_EMPLOYEE_SALARY
	CHECK(SALARY IS NOT NULL);

ALTER TABLE C_EMPLOYEE
ADD CONSTRAINT NN_C_EMPLOYEE_ADDRESS
	CHECK(ADDRESS IS NOT NULL);

ALTER TABLE C_DEPARTMENT
ADD CONSTRAINT NN_C_DEPARTMENT_MGR_SSN
	CHECK(MGR_SSN IS NOT NULL);

ALTER TABLE C_DEPT_LOCATION
ADD CONSTRAINT NN_C_DEPT_LOCATION_NUM
	CHECK(DEPT_LOCATION_NUM IS NOT NULL);

ALTER TABLE C_PROJECTS
ADD CONSTRAINT NN_C_PROJECTS_DEPT_NUM
	CHECK(PROJ_DEPT_NUM IS NOT NULL);

ALTER TABLE C_WORKS_ON
ADD CONSTRAINT NN_C_WORKS_ON_ESSN
	CHECK(ESSN IS NOT NULL);

ALTER TABLE C_WORKS_ON
ADD CONSTRAINT NN_C_WORKS_ON_PNO
	CHECK(P_NUM IS NOT NULL);

ALTER TABLE C_DEPENDENTS
ADD CONSTRAINT NN_C_DEPENDENTS
	CHECK(ESSN IS NOT NULL);
--*******************************
--END OF COMPANY DATABASE
--*******************************
